<?php
return ['plural-forms'=>'nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100 >= 3 && n%100<=10 ? 3 : n%100 >= 11 && n%100<=99 ? 4 : 5;','project-id-version'=>'Greenpeace Planet 4 Master Theme','pot-creation-date'=>'2018-12-13 11:03+0000','po-revision-date'=>'2025-02-20 14:32+0000','language-team'=>'Arabic','mime-version'=>'1.0','content-type'=>'text/plain; charset=UTF-8','content-transfer-encoding'=>'8bit','x-generator'=>'Loco https://localise.biz/','x-poedit-basepath'=>'..','x-poedit-flags-xgettext'=>'--add-comments=translators:','x-poedit-wpheader'=>'style.css','x-poedit-sourcecharset'=>'UTF-8','x-poedit-keywordslist'=>'__;_e;_n:1,2;_x:1,2c;_ex:1,2c;_nx:4c,1,2;esc_attr__;esc_attr_e;esc_attr_x:1,2c;esc_html__;esc_html_e;esc_html_x:1,2c;_n_noop:1,2;_nx_noop:3c,1,2;__ngettext_noop:1,2','last-translator'=>'','language'=>'ar','report-msgid-bugs-to'=>'','x-loco-version'=>'2.7.1; wp-6.7.2','x-poedit-searchpath-0'=>'.','x-poedit-searchpathexcluded-0'=>'*.js
','messages'=>['%1$d result for \'%2$s\''=>'هي نتيجة' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '','%d result'=>'٪ د النتيجة' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '' . "\0" . '','.'=>'.','404 Page'=>'عذراً الصفحة التي تبحث عنها غير موجودة بالموقع الرجاء التأكد من عنوان الصفحة','About Greenpeace'=>'عن غرينبيس','about the author'=>'نبذة عن الكاتب','Act'=>'تحرك','ACTION'=>'تحرُك','Action'=>'تحرُك','ACTIVE FILTERS'=>'الفلاتر المفعّلة','Apply filters'=>'طبق الفلاتر','Archive'=>'أرشيف','Archive URL'=>'عنوان الأرشيف','Articles'=>'مقالات','CAMPAIGN'=>'حملة','Campaign'=>'حملة','Cancel'=>'إلغاء','CATEGORY'=>'الفئة','Category'=>'الفئة','Change Country'=>'غّير البلد','Check for typos, and try your search again'=>'تحقق من الأخطاء المطبعية ، وحاول البحث مرة أخرى','Clear all'=>'امسح الكل','Close Menu'=>'إغلق القائمة','Comment'=>'تعليق','Comments'=>'تعليقات','Content type'=>'نوع المحتوى','CONTENT TYPES'=>'أنواع المحتويات','Discussion'=>'نقاش','DOCUMENT'=>'ملف','Document'=>'ملف','Donate'=>'تبرع','Download'=>'حمل','Email'=>'البريد الإلكتروني','Enter your search term below'=>'أدخل مصطلح البحث الخاص بك أدناه','Evergreen Page'=>'صفحة خضراء','Explore'=>'إكتشف','Filters'=>'فلاتر','Got it!'=>'واضح!','Greenpeace International'=>'غرينبيس الدولية','Greenpeace Planet 4 Master Theme'=>'الموضوع الرئيسي لغرينبيس بلانيت 4','https://github.com/greenpeace'=>'https://github.com/greenpeace','https://github.com/greenpeace/planet4-master-theme'=>'https://github.com/greenpeace/planet4-master-theme','International (English)'=>'الموقع الدولي (باللغة الإنجليزية)','ISSUE'=>'المسألة','Issue'=>'المسألة','Leave your reply'=>'اكتب ردك','Load More'=>'تحميل المزيد','Manage'=>'إدارة','Master theme for the Planet 4 Wordpress project'=>'الموضوع الرئيسي لمشروع ووردبرس بلانيت 4','Menu'=>'قائمة','Most relevant'=>'الأكثر صلة
','Name'=>'اسم','Newest'=>'الأحدث','Oldest'=>'الأقدم','PAGE'=>'صفحة','Page'=>'صفحة','POST'=>'انشر','Post'=>'المنشور','Post comment'=>'أضف تعليقا
','Posts by '=>'نشر بواسطة','Publications'=>'المنشورات','Read More'=>'اقرأ المزيد','Refine your search'=>'حدد نطاق البحث
','Related Campaigns'=>'الحملات ذات الصلة','Results'=>'النتائج','Search'=>'بحث','Selected'=>'المحدد','Share on'=>'شارك على','Share via'=>'شارك عبر','Show %s more results'=>'عرض %s المزيد','Sitemap Page'=>'خريطة الموقع
','Skip to Content'=>'تخطى الى المحتوى','Skip to Footer'=>'انتقل إلى تذييل الصفحة','Skip to Navigation'=>'تخطى إلى التنقل','Sorry, we can\'t find that page!'=>'عذرا ، لا يمكننا العثور على تلك الصفحة!','Sort by'=>'ترتيب حسب
','Submit'=>'إرسال','Suggested search terms'=>'مصطلحات البحث المقترحة
','Take action'=>'تحرك الأن','Things you can do'=>'أشياء تستطيع فعلها','This Campaign is not assigned to an Issue'=>'لم يتم تعيين هذه الحملة لمشكلة
','To see the content of this page, please enter your password  below'=>'لرؤية محتوى هذه الصفحة، يرجى إدخال كلمة المرور الخاصة بك أدناه','Toggle navigation menu'=>'تبديل قائمة التنقل
','Toggle search box'=>'تبديل مربع البحث','Toggle search form'=>'تبديل نموذج البحث','Toggle worldwide site selection menu'=>'تبديل قائمة اختيار الموقع إلى جميع أنحاء العالم','Try searching for somthing else'=>'حاول البحث عن شيء آخر','We also included results for '=>'لقد قمنا أيضًا بتضمين نتائج لـ
','We want you to take action because together we\'re strong.'=>'نريدك أن تتخذ إجراءً لأننا معاً نكون أقوى.','We\'re sorry we couldn\'t find any matches for your search term.'=>'نأسف لعدم العثور على أي مطابقات لعبارة البحث.
','Worldwide site list'=>'قائمة المواقع العالمية','Your Comment'=>'تعليقك','Your Email'=>'بريدك الالكتروني','Your Name'=>'اسمك']];
