FROM mcr.microsoft.com/playwright:v1.30.0 as playwright

WORKDIR /usr/app
RUN npm install @playwright/test
RUN npx playwright install --with-deps

FROM playwright AS playwright-ci

ARG theme_branch=main
ARG plugin_branch=main

RUN git clone -b $theme_branch --single-branch https://github.com/greenpeace/planet4-master-theme
RUN git clone -b $plugin_branch --single-branch https://github.com/greenpeace/planet4-plugin-gutenberg-blocks
