# Ref: https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github#custom-configuration
have_fun: false
code_review:
  disable: true
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: false
